version: "3.7"
services:
  # goapp:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     - ./data:/home/go/app/data:cached
  #   command: go build
  #   ports:
  #     - 9765:9765
  nodeapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./nodeserver/data:/home/node/app/data:cached
    command: npm run start
    ports:
      - 9765:9765
